### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by eye0fra**
istio security greeting service run with sa-greeting account.

### CODE REVIEW

**Comment by geoand** [comment]
Hi,

could you perhaps add the reason why these changes are needed?

Thanks

**Comment by eye0fra** [comment]
Hi @geoand,

Sure when deploying an application into a Service Mesh running in an OpenShift, it is currently necessary to relax the security constraints by its service account to ensure the application can function correctly. 
Each service account must be granted permissions with the anyuid and privileged Security Context Constraints (SCC) to enable the sidecars to run correctly.


Otherwise you will hit the following errors:

Failed Create | (combined from similar events): Error creating: pods "spring-boot-istio-security-greeting-5-gfd2f" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000570000, 1000579999] spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 1337: must be in the ranges: [1000570000, 1000579999]]
-- | --

**Comment by geoand** [comment]
Cool! Could you perhaps add the gist of that explanation to the readme so users can know why they need to execute this commands (since it is not obvious)

**Comment by eye0fra** [comment]
Or we can use the official docs :)

https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#configuring-security-constraints-for-application-service-accounts

**Comment by geoand** [comment]
Good idea. So I guess a very small explanation and then a link to that doc

**Comment by eye0fra** [comment]
Ok I push it, let me know if it's ok now!

**Comment by geoand** [comment]
Looks good, thanks!

**Pull request merged**
