### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by lincolnthree**

### CODE REVIEW

**Comment by lincolnthree** [comment]
I don't see a scenario 3 in my PR? Feel free to update as needed or just steal this code and put it in.

**Comment by lincolnthree** [comment]
Oh, *this* PR... Yeah. Just take scenario 3 out and you should be good to go?

**Comment by gytis** [comment]
Seems like you need to rebase

**Comment by lincolnthree** [comment]
Done. Please review!

---
Lincoln Baxter, III
Principal Software Engineer
http://developers.redhat.com

**Pull request closed without merging**
